---
#Este playbook es para llamar al rol osp-servers 
#This Playbook it to call role for osp-servers

- hosts: localhost
  connection: local
  become: no
  gather_facts: true
  roles:
   - osp-servers
